# Generated by Django 5.2.1 on 2026-05-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_end_time_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_reminder_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_reminder_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
