# Generated by Django 5.2.1 on 2026-05-23 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorDecor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_area', models.CharField(default='Main Floor', max_length=80)),
                ('decor_type', models.CharField(choices=[('wall', 'Wall'), ('plant', 'Plant'), ('bar', 'Bar'), ('kitchen', 'Kitchen'), ('door', 'Door'), ('note', 'Note')], default='plant', max_length=30)),
                ('label', models.CharField(blank=True, max_length=120, null=True)),
                ('pos_x', models.IntegerField(default=80)),
                ('pos_y', models.IntegerField(default=80)),
                ('pos_width', models.IntegerField(default=120)),
                ('pos_height', models.IntegerField(default=80)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floor_decors', to='restaurants.branch')),
            ],
        ),
    ]
