# Generated by Django 5.2.1 on 2026-05-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='waiter_pin',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
