# Generated by Django 5.2.1 on 2026-05-21 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='UZS', max_length=10)),
                ('timezone', models.CharField(default='Asia/Tashkent', max_length=100)),
                ('language', models.CharField(default='uz', max_length=20)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('service_fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('auto_print_receipt', models.BooleanField(default=False)),
                ('enable_split_bill', models.BooleanField(default=True)),
                ('enable_qr_menu', models.BooleanField(default=True)),
                ('auto_send_kitchen', models.BooleanField(default=True)),
                ('kitchen_sound_alerts', models.BooleanField(default=True)),
                ('low_stock_alert', models.BooleanField(default=True)),
                ('auto_inventory_deduction', models.BooleanField(default=True)),
                ('shift_management', models.BooleanField(default=True)),
                ('attendance_tracking', models.BooleanField(default=True)),
                ('enable_accounting', models.BooleanField(default=True)),
                ('fiscal_year_start', models.DateField(blank=True, null=True)),
                ('receipt_footer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='restaurants.branch')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='restaurants.restaurant')),
            ],
        ),
    ]
