# Generated by Django 5.2.1 on 2026-05-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='receipt_header',
            field=models.CharField(default='Premium Restaurant OS', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='receipt_show_waiter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='waiter_commission_percent',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
