# Generated by Django 5.2.1 on 2026-05-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0002_systemsettings_receipt_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='rub_to_base_rate',
            field=models.DecimalField(decimal_places=2, default=135, max_digits=12),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='usd_to_base_rate',
            field=models.DecimalField(decimal_places=2, default=12020, max_digits=12),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='waiter_daily_fixed_pay',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=12),
        ),
    ]
