# Generated by Django 5.2.1 on 2026-05-23 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_historicalorder_completed_at_order_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='held_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='merged_into',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.order'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='printer_route',
            field=models.CharField(default='kitchen', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='priority_flag',
            field=models.CharField(choices=[('normal', 'Normal'), ('rush', 'Rush'), ('vip', 'VIP')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='refund_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='source_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.order'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='void_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalorderitem',
            name='course',
            field=models.CharField(choices=[('starter', 'Starter'), ('main', 'Main'), ('dessert', 'Dessert'), ('drinks', 'Drinks')], default='main', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalorderitem',
            name='guest_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='held_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_orders', to='orders.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='printer_route',
            field=models.CharField(default='kitchen', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='priority_flag',
            field=models.CharField(choices=[('normal', 'Normal'), ('rush', 'Rush'), ('vip', 'VIP')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='source_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_orders', to='orders.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='void_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='course',
            field=models.CharField(choices=[('starter', 'Starter'), ('main', 'Main'), ('dessert', 'Dessert'), ('drinks', 'Drinks')], default='main', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='guest_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('held', 'Held'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('held', 'Held'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.table'),
        ),
    ]
