# Generated by Django 5.2.1 on 2026-05-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_historicalorder_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='service_charge_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='service_charge_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
