# Generated by Django 5.2.1 on 2026-05-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_historicalorder_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='guest_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='historicalorderitem',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalorderitem',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
    ]
