# Generated by Django 5.2.1 on 2026-05-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_historicalorder_guest_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltable',
            name='floor_area',
            field=models.CharField(default='Main Floor', max_length=80),
        ),
        migrations.AddField(
            model_name='historicaltable',
            name='pos_height',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='historicaltable',
            name='pos_width',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='historicaltable',
            name='pos_x',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='historicaltable',
            name='pos_y',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='table',
            name='floor_area',
            field=models.CharField(default='Main Floor', max_length=80),
        ),
        migrations.AddField(
            model_name='table',
            name='pos_height',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='table',
            name='pos_width',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='table',
            name='pos_x',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='table',
            name='pos_y',
            field=models.IntegerField(default=120),
        ),
    ]
